apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: declarative
spec:
  project: default
  source:
    repoURL: https://github.com/kothakapu-srinvas/gitops-demo.git
    targetRevision: HEAD
    path: ./declarative/manifest/deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
